# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e27a26267714f8f3908ecac85a0c10ee99c2d52dd37173234927a787e31ecfaa0094f854044d15f50d9241241f70442b196cf6f622c221ccaa463d3fc7f4cf66

test:
  secret_key_base: 5be5aedaf24d677dd4cddbdeaadae9f23e58fd2fbd258bd71cd8042781357576e45d6699105493c14598ca62bb5769568954d207d770c3e3b36a467a179008f6

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
